AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy Flask app on EC2 instance with all the required security groups, permissions and IAM roles.
 
    
Resources:
  CloudTermAssignment:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and port 5000 access from anywhere
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5050
          ToPort: 5050
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0   
 
  EC2Profile:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: AccessS3Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "logs:*"
                Resource: "*"
              - Effect: Allow
                Action: "s3:*"
                Resource: "*"
 
  EC2InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - !Ref EC2Profile
 
  CloudTermAssignmentInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      SecurityGroupIds:
        - Ref: CloudTermAssignment
      ImageId: "ami-051f8a213df8bc089"
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y git
          sudo yum install -y python3-pip
          python3 -m pip install --upgrade pip
          sudo mkdir cloudComputingTermAssignment_jahnavi
          cd cloudComputingTermAssignment_jahnavi
          sudo git clone https://github.com/JahnaviGajjala/CloudComputingTermAssignmentJahnavi.git
          cd CloudComputingTermAssignmentJahnavi/termassign # Update this path if your repo structure is different
          sudo python3 -m venv venv
          source venv/bin/activate
          sudo pip install -r requirements.txt
          sudo FLASK_APP=app.py FLASK_RUN_PORT=5050 FLASK_RUN_HOST=0.0.0.0 flask run &
 
Outputs:
  WebsiteURL:
    Description: "URL for the Term Assignment Flask app"
    Value: !Sub "http://${CloudTermAssignmentInstance.PublicDnsName}:5050"
GitHub - JahnaviGajjala/CloudComputingTermAssignmentJahnavi
Contribute to JahnaviGajjala/CloudComputingTermAssignmentJahnavi development by creating an account on GitHub.